version: "3.8"

services:

  db:
    container_name: db
    image: postgres:15.1-alpine
#    volumes:
#      - ./psql:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
#    volumes:
#      - ./psql:/var/lib/postgresql/data/
#    env_file:
#      - .env
    networks:
      - app_network
    expose:
      - "5432"
#    ports:
#      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 10s
      timeout: 3s
      retries: 5

  app:
    container_name: menu_app
    build:
      context: .
      dockerfile: Dockerfile
#    volumes:
#      - shared:menu_catalog/reports
#    env_file:
#      - .env
    entrypoint: >
      sh -c "
        echo 'Making migrations...' &&
        alembic upgrade head &&
        echo 'Starting project...' &&
        uvicorn app.main:app --host 0.0.0.0 --reload
      "
    networks:
      - app_network
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy

networks:
  app_network:
    name: app_network