version: "3.8"

services:

  db:
    container_name: db
    image: postgres:15.1-alpine
    environment:
      DPOSTGRES_NAME: $POSTGRES_NAME
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_PORT: $POSTGRES_PORT
    networks:
      - app_network
    expose:
      - $POSTGRES_PORT
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_NAME} -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 3s
      retries: 5

  app:
    container_name: menu_app
    build:
      context: .
      dockerfile: app/Dockerfile
    entrypoint: >
      sh -c "
        echo 'Making migrations...' &&
        alembic upgrade head &&
        echo 'Starting project...' &&
        uvicorn app.main:app --host 0.0.0.0 --reload
      "
    networks:
      - app_network
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy

networks:
  app_network:
    name: app_network