version: "3.8"

services:

  db:
    container_name: db
    image: postgres:15.1-alpine
    volumes:
      - ./psql:/var/lib/postgresql/data/
    env_file:
      - .env
    networks:
      - web_app_network
    expose:
      - '5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 3

  menu_catalog:
    container_name: menu_catalog
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    entrypoint: >
      sh -c "
        python main.py
      "
    networks:
      - web_app_network
    ports:
      - 8000:8000
    depends_on:
      web_app_db:
        condition: service_healthy

networks:
  web_app_network:
    name: web_app_network